# Site settings
title: IanLecture
url: "https://goodgodgd.github.io/ian-lecture"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/ian-lecture" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Seoul
description: >
  Lecture materials by Hyukdoo Choi

# Your information
email: hyukdoo.choi@sch.ac.kr
author: Hyukdoo Choi
profile: SCH EI eng. professor
github_username: goodgodgd
profile_links:
  Email: "mailto:hyukdoo.choi@sch.ac.kr"
  # You can add more profile links above, or edit _includes/sidebar.html 

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5         # posts per page
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

avatar: "/ian-lecture/assets/sidebar/avatar.jpg"

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
